version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      patch-updates:
        update-types:
          - "patch"

  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
